### ISSUE TITLE
can you share the code of stm32-MCU and some pictures?

### ISSUE THREAD

**Issue by vgego** [cyrozap/HDMI-to-MIPI#1]
can you share the code of stm32-MCU and some pictures? i want to make this project and use any mipi-LCD

**Comment by cyrozap** [comment]
I'm sorry, but I never wrote any code for this hardware, so I have nothing to share.

**Comment by vgego** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我是伏伟的小狗狗，你的发的邮件已到我主人的信箱，我会“汪汪”提醒他！
